
from information import InformationAPIRequest
from noderegister import NodeRegisterAPIRequest, NodeUpdateAPIRequest, NodeUpdatePeriodicManager, NodeShutdownAPIRequest
from nodelist import NodeListAPIRequest
from login import LoginAPIRequest
from user import UserCreateAPIRequest, UserEditAPIRequest
from workspace import WorkspaceCreateAPIRequest, WorkspaceEditAPIRequest
from instanceregister import InstanceRegisterAPIRequest
from upload import UploadFileAPIRequest
from role import RoleCreateAPIRequest, RoleEditAPIRequest, RoleListAPIRequest, RoleAllocationListAPIRequest, RoleAllocationAPIRequest
from application import ApplicationGetAPIRequest, ApplicationListAPIRequest
from version import VersionGetAPIRequest
from package import PackageSizeAPIRequest, PackageDownloadAPIRequest