
from selectlocations import SelectLocationsJob
from register import RegisterRootJob, RegisterRequestJob
from storeport import StorePortJob
from startuproot import StartupRootJob
from shutdownroot import ShutdownRootJob
from deregisterroot import DeRegisterRootJob
from currentroot import CurrentVersionRootJob, CurrentVersionContainerJob