
from selectlocations import SelectLocationsJob
from register import RegisterRootJob, RegisterRequestJob
from storeport import StorePortJob
from startup import StartupRootJob, StartupRequestJob
from shutdown import ShutdownRootJob, ShutdownRequestJob
from deregisterroot import DeRegisterRootJob
from currentroot import CurrentVersionRootJob, CurrentVersionContainerJob